FROM vladistan/gradle:plus_ant


RUN adduser -q --gecos "" --home /app --uid 200 --disabled-password user < /dev/null
RUN adduser -q --gecos "" --home /app --uid 498 --disabled-password go < /dev/null
RUN adduser -q --gecos "" --home /app --uid 1000 --disabled-password ec2-user < /dev/null

